18:51:35,273 rospy.internal INFO topic[/step_done] adding connection to [http://simone-Aspire-V3-772G:34089/], count 0
18:51:35,275 rospy.internal INFO topic[/collision_count] adding connection to [http://simone-Aspire-V3-772G:34089/], count 0
18:51:35,367 rospy.internal INFO topic[/next_step] adding connection to [/server_endpoint], count 0
18:51:35,465 rospy.internal INFO topic[/rosout] adding connection to [/rosout], count 0
18:51:54,481 root INFO START TRIAL WITH HOLO
18:52:06,821 root INFO Step 1: 11.2347252368927
18:52:17,70 root INFO Step 2: 8.82841444015503
18:52:27,90 root INFO Step 3: 9.198140144348145
18:52:41,165 root INFO Step 4: 12.791990995407104
18:52:42,776 root INFO Reset count: 0
18:52:42,776 root INFO END TRIAL
18:52:42,811 root INFO Collisions: 2
18:52:44,316 root INFO START TRIAL WITHOUT HOLO
18:52:55,714 root INFO Step 1: 10.244737386703491
18:53:09,116 root INFO Step 2: 12.075122356414795
18:53:23,28 root INFO Step 3: 12.486981868743896
18:54:03,768 root INFO Step 4: 39.35623240470886
18:54:05,792 root INFO Reset count: 1
18:54:05,793 root INFO END TRIAL
18:54:05,836 root INFO Collisions: 28
18:54:09,522 rospy.core INFO signal_shutdown [atexit]
18:54:09,530 rospy.internal INFO topic[/rosout] removing connection to /rosout
18:54:09,530 rospy.internal INFO topic[/next_step] removing connection to /server_endpoint
18:54:09,531 rospy.internal INFO topic[/step_done] removing connection to http://simone-Aspire-V3-772G:34089/
18:54:09,532 rospy.internal WARNING Unknown error initiating TCP/IP socket to simone-Aspire-V3-772G:34891 (http://simone-Aspire-V3-772G:34089/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 560, in connect
    self.socket.connect((dest_addr, dest_port))
ConnectionRefusedError: [Errno 111] Connection refused

18:54:09,532 rospy.internal INFO topic[/collision_count] removing connection to http://simone-Aspire-V3-772G:34089/
18:54:09,532 rospy.internal WARNING Unknown error initiating TCP/IP socket to simone-Aspire-V3-772G:34891 (http://simone-Aspire-V3-772G:34089/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 560, in connect
    self.socket.connect((dest_addr, dest_port))
OSError: [Errno 9] Bad file descriptor

18:54:09,533 rospy.internal INFO topic[/collision_count] removing connection to http://simone-Aspire-V3-772G:34089/
18:54:09,533 rospy.impl.masterslave INFO atexit
