16:22:14,797 rospy.internal INFO topic[/step_done] adding connection to [http://simone-Aspire-V3-772G:37033/], count 0
16:22:14,798 rospy.internal INFO topic[/collision_count] adding connection to [http://simone-Aspire-V3-772G:37033/], count 0
16:22:14,813 rospy.internal INFO topic[/next_step] adding connection to [/server_endpoint], count 0
16:22:15,15 rospy.internal INFO topic[/rosout] adding connection to [/rosout], count 0
16:22:42,833 rospy.core INFO signal_shutdown [atexit]
16:22:42,841 rospy.internal INFO topic[/rosout] removing connection to /rosout
16:22:42,841 rospy.internal INFO topic[/next_step] removing connection to /server_endpoint
16:22:42,842 rospy.internal INFO topic[/step_done] removing connection to http://simone-Aspire-V3-772G:37033/
16:22:42,846 rospy.internal WARNING Unknown error initiating TCP/IP socket to simone-Aspire-V3-772G:43983 (http://simone-Aspire-V3-772G:37033/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/noetic/lib/python3/dist-packages/rosgraph/network.py", line 357, in read_ros_handshake_header
    d = sock.recv(buff_size)
ConnectionResetError: [Errno 104] Connection reset by peer

16:22:42,846 rospy.internal INFO topic[/collision_count] removing connection to http://simone-Aspire-V3-772G:37033/
16:22:42,847 rospy.impl.masterslave INFO atexit
