16:05:12,81 rospy.internal INFO topic[/step_done] adding connection to [http://simone-Aspire-V3-772G:46231/], count 0
16:05:12,81 rospy.internal INFO topic[/collision_count] adding connection to [http://simone-Aspire-V3-772G:46231/], count 0
16:05:12,170 rospy.internal INFO topic[/next_step] adding connection to [/server_endpoint], count 0
16:05:12,266 rospy.internal INFO topic[/rosout] adding connection to [/rosout], count 0
16:05:15,562 rospy.core INFO signal_shutdown [atexit]
16:05:15,571 rospy.internal INFO topic[/rosout] removing connection to /rosout
16:05:15,571 rospy.internal INFO topic[/next_step] removing connection to /server_endpoint
16:05:15,571 rospy.internal INFO topic[/step_done] removing connection to http://simone-Aspire-V3-772G:46231/
16:05:15,574 rospy.internal WARNING Unknown error initiating TCP/IP socket to simone-Aspire-V3-772G:38983 (http://simone-Aspire-V3-772G:46231/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/noetic/lib/python3/dist-packages/rosgraph/network.py", line 357, in read_ros_handshake_header
    d = sock.recv(buff_size)
ConnectionResetError: [Errno 104] Connection reset by peer

16:05:15,574 rospy.internal WARNING Unknown error initiating TCP/IP socket to simone-Aspire-V3-772G:38983 (http://simone-Aspire-V3-772G:46231/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/noetic/lib/python3/dist-packages/rosgraph/network.py", line 357, in read_ros_handshake_header
    d = sock.recv(buff_size)
ConnectionResetError: [Errno 104] Connection reset by peer

16:05:15,576 rospy.internal INFO topic[/collision_count] removing connection to http://simone-Aspire-V3-772G:46231/
16:05:15,576 rospy.internal INFO topic[/collision_count] removing connection to http://simone-Aspire-V3-772G:46231/
16:05:15,577 rospy.topics ERROR Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 326, in close
    c.close()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 846, in close
    self.socket.close()
AttributeError: 'NoneType' object has no attribute 'close'

16:05:15,578 rospy.impl.masterslave INFO atexit
16:05:38,578 rospy.internal INFO topic[/collision_count] adding connection to [http://simone-Aspire-V3-772G:38593/], count 0
16:05:38,585 rospy.internal INFO topic[/step_done] adding connection to [http://simone-Aspire-V3-772G:38593/], count 0
16:05:38,653 rospy.internal INFO topic[/next_step] adding connection to [/server_endpoint], count 0
16:05:38,753 rospy.internal INFO topic[/rosout] adding connection to [/rosout], count 0
16:07:19,48 root INFO Human finished in: 60.77922320365906
16:07:19,49 root INFO Step 1: 60.78017568588257
16:07:52,882 root INFO Human finished in: 30.91072940826416
16:07:52,934 root INFO Step 2: 30.96215558052063
16:08:18,136 root INFO Step 3: 22.43070673942566
16:08:18,141 root INFO Human finished in: 22.43494462966919
16:08:48,80 root INFO Human finished in: 26.720722913742065
16:08:48,81 root INFO Step 4: 26.72172260284424
16:08:53,56 root INFO Reset count: 0
16:08:53,61 root INFO END TRIAL
16:08:53,208 root INFO Collisions: 1
16:08:54,938 root INFO START TRIAL WITH HOLO
16:09:29,126 root INFO Human finished in: 24.56177806854248
16:09:31,456 root INFO Step 1: 26.891602516174316
16:10:01,971 root INFO Human finished in: 20.28966522216797
16:10:07,34 root INFO Step 2: 25.352703094482422
16:10:36,607 root INFO Human finished in: 25.32151484489441
16:10:36,658 root INFO Step 3: 25.372157096862793
16:11:01,831 root INFO Human finished in: 22.57032561302185
16:11:01,832 root INFO Step 4: 22.571226596832275
16:11:04,933 root INFO Reset count: 0
16:11:04,933 root INFO END TRIAL
16:11:05,18 root INFO Collisions: 4
16:11:18,637 rospy.core INFO signal_shutdown [atexit]
16:11:18,647 rospy.internal INFO topic[/rosout] removing connection to /rosout
16:11:18,647 rospy.internal INFO topic[/next_step] removing connection to /server_endpoint
16:11:18,648 rospy.internal ERROR Unable to initiate TCP/IP socket to simone-Aspire-V3-772G:46657 (http://simone-Aspire-V3-772G:38593/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 600, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
rospy.exceptions.TransportInitError: remote error reported: node shutting down

16:11:18,649 rospy.internal WARNING Unknown error initiating TCP/IP socket to simone-Aspire-V3-772G:46657 (http://simone-Aspire-V3-772G:38593/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/noetic/lib/python3/dist-packages/rosgraph/network.py", line 357, in read_ros_handshake_header
    d = sock.recv(buff_size)
ConnectionResetError: [Errno 104] Connection reset by peer

16:11:18,649 rospy.internal INFO topic[/step_done] removing connection to http://simone-Aspire-V3-772G:38593/
16:11:18,649 rospy.internal INFO topic[/step_done] removing connection to http://simone-Aspire-V3-772G:38593/
16:11:18,649 rospy.topics ERROR Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 326, in close
    c.close()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 846, in close
    self.socket.close()
AttributeError: 'NoneType' object has no attribute 'close'

16:11:18,649 rospy.internal INFO topic[/collision_count] removing connection to http://simone-Aspire-V3-772G:38593/
16:11:18,651 rospy.impl.masterslave INFO atexit
